In [10]:
import numpy as np
import pandas as pd 
housing = pd.read_csv('./dataFile/housing.csv')
housing["income_cat"] = np.ceil(housing["median_income"]/1.5)
housing["income_cat"].where(housing["income_cat"]<5, 5.0, inplace=True)


In [11]:
print(housing["median_income"])

0        8.3252
1        8.3014
2        7.2574
3        5.6431
4        3.8462
5        4.0368
6        3.6591
7        3.1200
8        2.0804
9        3.6912
10       3.2031
11       3.2705
12       3.0750
13       2.6736
14       1.9167
15       2.1250
16       2.7750
17       2.1202
18       1.9911
19       2.6033
20       1.3578
21       1.7135
22       1.7250
23       2.1806
24       2.6000
25       2.4038
26       2.4597
27       1.8080
28       1.6424
29       1.6875
          ...  
20610    1.3631
20611    1.2857
20612    1.4934
20613    1.4958
20614    2.4695
20615    2.3598
20616    2.0469
20617    3.3021
20618    2.2500
20619    2.7303
20620    4.5625
20621    2.3661
20622    2.4167
20623    2.8235
20624    3.0739
20625    4.1250
20626    2.1667
20627    3.0000
20628    2.5952
20629    2.0943
20630    3.5673
20631    3.5179
20632    3.1250
20633    2.5495
20634    3.7125
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: median_income, Len

In [12]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]


In [13]:
housing['income_cat'].value_counts()/ len(housing)

3.0    0.350581
2.0    0.318847
4.0    0.176308
5.0    0.114438
1.0    0.039826
Name: income_cat, dtype: float64

In [14]:
for set_ in(strat_train_set, strat_test_set):
    set_.drop("income_cat", axis=1, inplace=True)

In [17]:
housing = strat_train_set.drop("median_house_value", axis=1)
print(strat_train_set["median_house_value"])
housing_labels = strat_train_set["median_house_value"].copy()

17606    286600.0
18632    340600.0
14650    196900.0
3230      46300.0
3555     254500.0
19480    127900.0
8879     500001.0
13685    140200.0
4937      95000.0
4861     500001.0
16365     92100.0
19684     61500.0
19234    313000.0
13956     89000.0
2390     123900.0
11176    197400.0
15614    500001.0
2953      63300.0
13209    107000.0
6569     184200.0
5825     280900.0
18086    500001.0
16718    171300.0
13600    116600.0
13989     60800.0
15168    121100.0
6747     270700.0
7398     109900.0
5562     159600.0
16121    500001.0
           ...   
12380    122500.0
5618     350000.0
10060    172800.0
18067    500001.0
4471     146600.0
19786     81300.0
9969     247600.0
14621    164100.0
579      254900.0
11682    185700.0
245      126800.0
12130    114200.0
16441    101800.0
11016    265600.0
19934     88900.0
1364     225000.0
1236     123500.0
5364     500001.0
11703    321600.0
10356    266000.0
15270    346700.0
3754     190200.0
12166    148800.0
6003     214800.0
7364     1

In [28]:
median = housing["total_bedrooms"].median()
housing["total_bedrooms"].fillna(median, inplace=True)

In [29]:
from sklearn.preprocessing import Imputer
imputer = Imputer(strategy="median")

In [35]:
housing_num = housing.drop("ocean_proximity", axis=1)
imputer.fit(housing_num)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='median', verbose=0)

In [33]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [34]:
housing_num.median().values

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [36]:
X = imputer.transform(housing_num)

In [1]:
#누락된 값 채워주기
from sklearn.preprocessing import Imputer
imputer = Imputer(strategy="median")

In [37]:
housing_num = housing.drop("ocean_proximity", axis=1)

In [38]:
imputer.fit(housing_num)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='median', verbose=0)

In [39]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [40]:
housing_num

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>longitude</th>
      <th>latitude</th>
      <th>housing_median_age</th>
      <th>total_rooms</th>
      <th>total_bedrooms</th>
      <th>population</th>
      <th>households</th>
      <th>median_income</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>17606</th>
      <td>-121.89</td>
      <td>37.29</td>
      <td>38.0</td>
      <td>1568.0</td>
      <td>351.0</td>
      <td>710.0</td>
      <td>339.0</td>
      <td>2.7042</td>
    </tr>
    <tr>
      <th>18632</th>
      <td>-121.93</td>
      <td>37.05</td>
      <td>14.0</td>
      <td>679.0</td>
      <td>108.0</td>
      <td>306.0</td>
      <td>113.0</td>
      <td>6.4214</td>
    </tr>
    <tr>
      <th>14650</th>
      <td>-117.20</td>
      <td>32.77</td>
      <td>31.0</td>
      <td>1952.0</td>
      <td>471.0</td>
      <td>936.0</td>
      <td>462.0</td>
      <td>2.8621</td>
    </tr>
    <tr>
      <th>3230</th>
      <td>-119.61</td>
      <td>36.31</td>
      <td>25.0</td>
      <td>1847.0</td>
      <td>371.0</td>
      <td>1460.0</td>
      <td>353.0</td>
      <td>1.8839</td>
    </tr>
    <tr>
      <th>3555</th>
      <td>-118.59</td>
      <td>34.23</td>
      <td>17.0</td>
      <td>6592.0</td>
      <td>1525.0</td>
      <td>4459.0</td>
      <td>1463.0</td>
      <td>3.0347</td>
    </tr>
    <tr>
      <th>19480</th>
      <td>-120.97</td>
      <td>37.66</td>
      <td>24.0</td>
      <td>2930.0</td>
      <td>588.0</td>
      <td>1448.0</td>
      <td>570.0</td>
      <td>3.5395</td>
    </tr>
    <tr>
      <th>8879</th>
      <td>-118.50</td>
      <td>34.04</td>
      <td>52.0</td>
      <td>2233.0</td>
      <td>317.0</td>
      <td>769.0</td>
      <td>277.0</td>
      <td>8.3839</td>
    </tr>
    <tr>
      <th>13685</th>
      <td>-117.24</td>
      <td>34.15</td>
      <td>26.0</td>
      <td>2041.0</td>
      <td>293.0</td>
      <td>936.0</td>
      <td>375.0</td>
      <td>6.0000</td>
    </tr>
    <tr>
      <th>4937</th>
      <td>-118.26</td>
      <td>33.99</td>
      <td>47.0</td>
      <td>1865.0</td>
      <td>465.0</td>
      <td>1916.0</td>
      <td>438.0</td>
      <td>1.8242</td>
    </tr>
    <tr>
      <th>4861</th>
      <td>-118.28</td>
      <td>34.02</td>
      <td>29.0</td>
      <td>515.0</td>
      <td>229.0</td>
      <td>2690.0</td>
      <td>217.0</td>
      <td>0.4999</td>
    </tr>
    <tr>
      <th>16365</th>
      <td>-121.31</td>
      <td>38.02</td>
      <td>24.0</td>
      <td>4157.0</td>
      <td>951.0</td>
      <td>2734.0</td>
      <td>879.0</td>
      <td>2.7981</td>
    </tr>
    <tr>
      <th>19684</th>
      <td>-121.62</td>
      <td>39.14</td>
      <td>41.0</td>
      <td>2183.0</td>
      <td>559.0</td>
      <td>1202.0</td>
      <td>506.0</td>
      <td>1.6902</td>
    </tr>
    <tr>
      <th>19234</th>
      <td>-122.69</td>
      <td>38.51</td>
      <td>18.0</td>
      <td>3364.0</td>
      <td>501.0</td>
      <td>1442.0</td>
      <td>506.0</td>
      <td>6.6854</td>
    </tr>
    <tr>
      <th>13956</th>
      <td>-117.06</td>
      <td>34.17</td>
      <td>21.0</td>
      <td>2520.0</td>
      <td>582.0</td>
      <td>416.0</td>
      <td>151.0</td>
      <td>2.7120</td>
    </tr>
    <tr>
      <th>2390</th>
      <td>-119.46</td>
      <td>36.91</td>
      <td>12.0</td>
      <td>2980.0</td>
      <td>495.0</td>
      <td>1184.0</td>
      <td>429.0</td>
      <td>3.9141</td>
    </tr>
    <tr>
      <th>11176</th>
      <td>-117.96</td>
      <td>33.83</td>
      <td>30.0</td>
      <td>2838.0</td>
      <td>649.0</td>
      <td>1758.0</td>
      <td>593.0</td>
      <td>3.3831</td>
    </tr>
    <tr>
      <th>15614</th>
    

In [41]:
imputer.fit(housing_num)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='median', verbose=0)

In [42]:
imputer.fit(housing_num)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='median', verbose=0)

In [27]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [43]:
X = imputer.transform(housing_num)

In [44]:
housing_tr = pd.DataFrame(X, columns=housing_num.columns,
                          index=list(housing.index.values))

In [45]:
housing_num.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [46]:
housing.index.values

array([17606, 18632, 14650, ..., 13908, 11159, 15775], dtype=int64)

In [47]:
housing

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>longitude</th>
      <th>latitude</th>
      <th>housing_median_age</th>
      <th>total_rooms</th>
      <th>total_bedrooms</th>
      <th>population</th>
      <th>households</th>
      <th>median_income</th>
      <th>ocean_proximity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>17606</th>
      <td>-121.89</td>
      <td>37.29</td>
      <td>38.0</td>
      <td>1568.0</td>
      <td>351.0</td>
      <td>710.0</td>
      <td>339.0</td>
      <td>2.7042</td>
      <td>&lt;1H OCEAN</td>
    </tr>
    <tr>
      <th>18632</th>
      <td>-121.93</td>
      <td>37.05</td>
      <td>14.0</td>
      <td>679.0</td>
      <td>108.0</td>
      <td>306.0</td>
      <td>113.0</td>
      <td>6.4214</td>
      <td>&lt;1H OCEAN</td>
    </tr>
    <tr>
      <th>14650</th>
      <td>-117.20</td>
      <td>32.77</td>
      <td>31.0</td>
      <td>1952.0</td>
      <td>471.0</td>
      <td>936.0</td>
      <td>462.0</td>
      <td>2.8621</td>
      <td>NEAR OCEAN</td>
    </tr>
    <tr>
      <th>3230</th>
      <td>-119.61</td>
      <td>36.31</td>
      <td>25.0</td>
      <td>1847.0</td>
      <td>371.0</td>
      <td>1460.0</td>
      <td>353.0</td>
      <td>1.8839</td>
      <td>INLAND</td>
    </tr>
    <tr>
      <th>3555</th>
      <td>-118.59</td>
      <td>34.23</td>
      <td>17.0</td>
      <td>6592.0</td>
      <td>1525.0</td>
      <td>4459.0</td>
      <td>1463.0</td>
      <td>3.0347</td>
      <td>&lt;1H OCEAN</td>
    </tr>
    <tr>
      <th>19480</th>
      <td>-120.97</td>
      <td>37.66</td>
      <td>24.0</td>
      <td>2930.0</td>
      <td>588.0</td>
      <td>1448.0</td>
      <td>570.0</td>
      <td>3.5395</td>
      <td>INLAND</td>
    </tr>
    <tr>
      <th>8879</th>
      <td>-118.50</td>
      <td>34.04</td>
      <td>52.0</td>
      <td>2233.0</td>
      <td>317.0</td>
      <td>769.0</td>
      <td>277.0</td>
      <td>8.3839</td>
      <td>&lt;1H OCEAN</td>
    </tr>
    <tr>
      <th>13685</th>
      <td>-117.24</td>
      <td>34.15</td>
      <td>26.0</td>
      <td>2041.0</td>
      <td>293.0</td>
      <td>936.0</td>
      <td>375.0</td>
      <td>6.0000</td>
      <td>INLAND</td>
    </tr>
    <tr>
      <th>4937</th>
      <td>-118.26</td>
      <td>33.99</td>
      <td>47.0</td>
      <td>1865.0</td>
      <td>465.0</td>
      <td>1916.0</td>
      <td>438.0</td>
      <td>1.8242</td>
      <td>&lt;1H OCEAN</td>
    </tr>
    <tr>
      <th>4861</th>
      <td>-118.28</td>
      <td>34.02</td>
      <td>29.0</td>
      <td>515.0</td>
      <td>229.0</td>
      <td>2690.0</td>
      <td>217.0</td>
      <td>0.4999</td>
      <td>&lt;1H OCEAN</td>
    </tr>
    <tr>
      <th>16365</th>
      <td>-121.31</td>
      <td>38.02</td>
      <td>24.0</td>
      <td>4157.0</td>
      <td>951.0</td>
      <td>2734.0</td>
      <td>879.0</td>
      <td>2.7981</td>
      <td>INLAND</td>
    </tr>
    <tr>
      <th>19684</th>
      <td>-121.62</td>
      <td>39.14</td>
      <td>41.0</td>
      <td>2183.0</td>
      <td>559.0</td>
      <td>1202.0</td>
      <td>506.0</td>
      <td>1.6902</td>
      <td>INLAND</td>
    </tr>
    <tr>
      <th>19234</th>
      <td>-122.69</td>
      <td>38.51</td>
      <td>18.0</td>
      <td>3364.0</td>
      <td>501.0</td>
      <td>1442.0</td>
      <td>506.0</td>
      <td>6.6854</td>
      <td>&lt;1H OCEAN</td>
    </tr>
    <tr>
      <th>13956</th>
      <td>-117.06</td>
      <td>34.17</td>
      <td>21.0</td>
      <td>2520.0</td>
      <td>582.0</td>
      <td>416.0</td>
      <td>151.0</td>
      <td>2.7120</td>
      <td>INLAND</td>
    </tr>
    <tr>
      <th>2390</th>
      <td>-119.46</td>
      <td>36.91</td>

In [48]:
#OneHot_Encoding
housing_cat = housing["ocean_proximity"]

In [49]:
housing_cat_encoded, housing_cat_categories = housing_cat.factorize()

[0 0 1 ... 2 0 3]


In [84]:
housing_cat_categories

Index(['<1H OCEAN', 'NEAR OCEAN', 'INLAND', 'NEAR BAY', 'ISLAND'], dtype='object')

In [85]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
housing_cat_1hot = encoder.fit_transform(housing_cat_encoded.reshape(-1,1))
housing_cat_1hot

<16512x5 sparse matrix of type '<class 'numpy.float64'>'
	with 16512 stored elements in Compressed Sparse Row format>

In [86]:
housing_cat_1hot.toarray()

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [125]:
#자신만의 변환기 만들기
from sklearn.base import BaseEstimator, TransformerMixin

# column index
rooms_ix, bedrooms_ix, population_ix, household_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

In [126]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
    ('imputer', Imputer(strategy='median')),
    ('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler()),
])

housing_num_tr = num_pipeline.fit_transform(housing_num)

In [127]:
from sklearn.base import BaseEstimator, TransformerMixin
# Create a class to select numerical or categorical columns 
# since Scikit-Learn doesn't handle DataFrames yet
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [128]:
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]
num_pipeline = Pipeline([
    ('selector', DataFrameSelector(num_attribs)),
    ('imputer', Imputer(strategy="median")),
    ('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler()),
])
cat_pipeline = Pipeline([
        ('selector', DataFrameSelector(cat_attribs)),
        ('cat_encoder', OneHotEncoder(sparse=False)),
    ])

In [139]:
housing_cat_encoded, housing_categories = housing['ocean_proximity'].factorize()

In [143]:
housing['ocean_proximity'] = housing_cat_encoded

In [144]:
housing

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>longitude</th>
      <th>latitude</th>
      <th>housing_median_age</th>
      <th>total_rooms</th>
      <th>total_bedrooms</th>
      <th>population</th>
      <th>households</th>
      <th>median_income</th>
      <th>ocean_proximity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>17606</th>
      <td>-121.89</td>
      <td>37.29</td>
      <td>38.0</td>
      <td>1568.0</td>
      <td>351.0</td>
      <td>710.0</td>
      <td>339.0</td>
      <td>2.7042</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18632</th>
      <td>-121.93</td>
      <td>37.05</td>
      <td>14.0</td>
      <td>679.0</td>
      <td>108.0</td>
      <td>306.0</td>
      <td>113.0</td>
      <td>6.4214</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14650</th>
      <td>-117.20</td>
      <td>32.77</td>
      <td>31.0</td>
      <td>1952.0</td>
      <td>471.0</td>
      <td>936.0</td>
      <td>462.0</td>
      <td>2.8621</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3230</th>
      <td>-119.61</td>
      <td>36.31</td>
      <td>25.0</td>
      <td>1847.0</td>
      <td>371.0</td>
      <td>1460.0</td>
      <td>353.0</td>
      <td>1.8839</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3555</th>
      <td>-118.59</td>
      <td>34.23</td>
      <td>17.0</td>
      <td>6592.0</td>
      <td>1525.0</td>
      <td>4459.0</td>
      <td>1463.0</td>
      <td>3.0347</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19480</th>
      <td>-120.97</td>
      <td>37.66</td>
      <td>24.0</td>
      <td>2930.0</td>
      <td>588.0</td>
      <td>1448.0</td>
      <td>570.0</td>
      <td>3.5395</td>
      <td>2</td>
    </tr>
    <tr>
      <th>8879</th>
      <td>-118.50</td>
      <td>34.04</td>
      <td>52.0</td>
      <td>2233.0</td>
      <td>317.0</td>
      <td>769.0</td>
      <td>277.0</td>
      <td>8.3839</td>
      <td>0</td>
    </tr>
    <tr>
      <th>13685</th>
      <td>-117.24</td>
      <td>34.15</td>
      <td>26.0</td>
      <td>2041.0</td>
      <td>293.0</td>
      <td>936.0</td>
      <td>375.0</td>
      <td>6.0000</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4937</th>
      <td>-118.26</td>
      <td>33.99</td>
      <td>47.0</td>
      <td>1865.0</td>
      <td>465.0</td>
      <td>1916.0</td>
      <td>438.0</td>
      <td>1.8242</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4861</th>
      <td>-118.28</td>
      <td>34.02</td>
      <td>29.0</td>
      <td>515.0</td>
      <td>229.0</td>
      <td>2690.0</td>
      <td>217.0</td>
      <td>0.4999</td>
      <td>0</td>
    </tr>
    <tr>
      <th>16365</th>
      <td>-121.31</td>
      <td>38.02</td>
      <td>24.0</td>
      <td>4157.0</td>
      <td>951.0</td>
      <td>2734.0</td>
      <td>879.0</td>
      <td>2.7981</td>
      <td>2</td>
    </tr>
    <tr>
      <th>19684</th>
      <td>-121.62</td>
      <td>39.14</td>
      <td>41.0</td>
      <td>2183.0</td>
      <td>559.0</td>
      <td>1202.0</td>
      <td>506.0</td>
      <td>1.6902</td>
      <td>2</td>
    </tr>
    <tr>
      <th>19234</th>
      <td>-122.69</td>
      <td>38.51</td>
      <td>18.0</td>
      <td>3364.0</td>
      <td>501.0</td>
      <td>1442.0</td>
      <td>506.0</td>
      <td>6.6854</td>
      <td>0</td>
    </tr>
    <tr>
      <th>13956</th>
      <td>-117.06</td>
      <td>34.17</td>
      <td>21.0</td>
      <td>2520.0</td>
      <td>582.0</td>
      <td>416.0</td>
      <td>151.0</td>
      <td>2.7120</td>
      <td>2</td>
    </tr>
    <tr>
      <th>2390</th>
      <td>-119.46</td>
      <td>36.91</td>
      <td>12.0</td>
      <td>2980.0</td>
      <td>495.0</td>
      <td>1184.0</td>
      <td>429.0</td>
      <td

In [145]:
from sklearn.pipeline import FeatureUnion

full_pipeline = FeatureUnion(transformer_list=[
    ("num_pipeline", num_pipeline),
    ("cat_pipeline", cat_pipeline)
])

housing_prepared = full_pipeline.fit_transform(housing)

In [146]:
housing_prepared

array([[-1.15604281,  0.77194962,  0.74333089, ...,  0.        ,
         0.        ,  0.        ],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.18684903, -1.34218285,  0.18664186, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.        ,
         0.        ,  0.        ],
       [-1.43579109,  0.99645926,  1.85670895, ...,  0.        ,
         1.        ,  0.        ]])

In [147]:
housing_prepared.shape

(16512, 16)

In [158]:
housing_labels = housing_prepared[:, 11:]
housing_prepared = housing_prepared[:, :11]    

In [159]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(housing_prepared, housinglabels)

ImportError: cannot import name '_check_large_sparse'